name: ci

on:
  push:
    branches:
      - 'main'
    paths:
      - 'backend/**'
      - 'frontendWeb/**'

jobs:
  tests:
    if: contains(github.event.commits.*.modified, 'backend/')
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ vars.DB_NAME }}
      DB_USER: ${{ vars.DB_USER }}
      DB_PASS: ${{ vars.DB_PASS }}
      DB_HOST: ${{ vars.DB_HOST }}
      DB_DIALECT: ${{ vars.DB_DIALECT }}
      SECRET_KEY:  ${{ vars.SECRET_KEY }}
      PORT: 3333 
      TOKENUTIL_SECRETKEY: ${{ vars.TOKENUTIL_SECRETKEY }} 
    steps:
      # Checkout do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Configuração do Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Substitua pela versão do Node.js usada no seu projeto

      # Instalar dependências
      - name: Install dependencies
        run: npm install
        working-directory: ./backend

      # Rodar os testes com Jest
      - name: Run Jest tests
        run: npm test
        working-directory: ./backend

  docker:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
     
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          

      # Build e Push Backend
      - name: Build and push
        if: contains(github.event.commits.*.modified, 'backend/')
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./backend
          tags: |
            thaisperlho/nera-api:latest

      # Build e Push Frontend
      - name: Build and push frontend image
        if: contains(github.event.commits.*.modified, 'frontendWeb/')
        uses: docker/build-push-action@v5
        with:
          push: true
          context: ./frontendWeb
          tags: |
            thaisperlho/nera-app:latest
        